import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { NextAuthProvider } from "./components/NextAuthProvider";
import Navbar from "./components/general/Navbar";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<NextAuthProvider>
					{/* <Navbar /> */}
					{children}
				</NextAuthProvider>
			</body>
		</html>
	);
}
